// TaurusMQ — Realistic mock data reflecting actual production system behavior
// All values represent plausible production state at 3 AM during an incident

import type { Queue, Job, Worker, Alert, EventStreamItem, MetricPoint, FlowNode } from './types';

const NOW = Date.now();
const mins = (n: number) => n * 60 * 1000;
const hrs  = (n: number) => n * 60 * 60 * 1000;

// ─── Metric series generators ────────────────────────────────────────────────
function genSeries(base: number, variance: number, points = 60, spike?: { at: number; val: number }): MetricPoint[] {
  return Array.from({ length: points }, (_, i) => {
    let v = base + (Math.random() - 0.5) * variance;
    if (spike && Math.abs(i - spike.at) < 3) v = spike.val;
    return { t: NOW - (points - i) * mins(1), v: Math.max(0, v) };
  });
}

export const throughputSeries = genSeries(320, 80, 60, { at: 45, val: 12 }); // spike at 45 = incident start
export const latencySeries    = genSeries(142, 40, 60, { at: 45, val: 4200 });
export const errorSeries      = genSeries(2, 2, 60, { at: 45, val: 38 });
export const p50Series        = genSeries(95, 20, 60);
export const p95Series        = genSeries(340, 60, 60, { at: 45, val: 3800 });
export const p99Series        = genSeries(890, 120, 60, { at: 45, val: 7600 });
export const queueDepthSeries = genSeries(1200, 300, 60, { at: 45, val: 8400 });
export const successSeries    = genSeries(97, 2, 60, { at: 45, val: 48 });
export const retrySeries      = genSeries(1.5, 1, 60, { at: 45, val: 22 });

// ─── Queues ───────────────────────────────────────────────────────────────────
export const QUEUES: Queue[] = [
  {
    name: 'email-notifications',
    health: 'healthy',
    healthScore: 94,
    isPaused: false,
    counts: { waiting: 47, active: 12, delayed: 230, failed: 3, completed: 48291, paused: 0 },
    throughput: 342,
    avgLatency: 88,
    p99Latency: 412,
    errorRate: 0.008,
    workerCount: 4,
    retryRate: 0.012,
  },
  {
    name: 'image-processing',
    health: 'critical',
    healthScore: 23,
    isPaused: false,
    counts: { waiting: 3847, active: 8, delayed: 12, failed: 891, completed: 12043, paused: 0 },
    throughput: 18,
    avgLatency: 4200,
    p99Latency: 12800,
    errorRate: 0.41,
    workerCount: 2,
    retryRate: 0.38,
  },
  {
    name: 'report-generation',
    health: 'degraded',
    healthScore: 61,
    isPaused: false,
    counts: { waiting: 124, active: 3, delayed: 88, failed: 47, completed: 3902, paused: 0 },
    throughput: 24,
    avgLatency: 8200,
    p99Latency: 31000,
    errorRate: 0.12,
    workerCount: 2,
    retryRate: 0.09,
  },
  {
    name: 'webhook-dispatch',
    health: 'healthy',
    healthScore: 88,
    isPaused: false,
    counts: { waiting: 12, active: 6, delayed: 0, failed: 8, completed: 92847, paused: 0 },
    throughput: 580,
    avgLatency: 42,
    p99Latency: 280,
    errorRate: 0.009,
    workerCount: 6,
    retryRate: 0.021,
  },
  {
    name: 'data-sync',
    health: 'healthy',
    healthScore: 79,
    isPaused: false,
    counts: { waiting: 8, active: 2, delayed: 340, failed: 11, completed: 7823, paused: 0 },
    throughput: 62,
    avgLatency: 1200,
    p99Latency: 4800,
    errorRate: 0.014,
    workerCount: 2,
    retryRate: 0.03,
  },
  {
    name: 'pdf-export',
    health: 'degraded',
    healthScore: 55,
    isPaused: true,
    counts: { waiting: 0, active: 0, delayed: 0, failed: 29, completed: 1204, paused: 56 },
    throughput: 0,
    avgLatency: 0,
    p99Latency: 0,
    errorRate: 0.19,
    workerCount: 0,
    retryRate: 0.17,
  },
];

// ─── Jobs ─────────────────────────────────────────────────────────────────────
export const JOBS: Job[] = [
  {
    id: 'job_8f3a92b1c4e7',
    name: 'process-upload',
    queueName: 'image-processing',
    state: 'failed',
    priority: 1,
    attempts: 3,
    maxAttempts: 3,
    progress: 0,
    data: { userId: 'usr_4f2a9', fileKey: 's3://tmq-uploads/2026/06/13/img_4k_raw.tiff', width: 4096, height: 3072, format: 'tiff', sizeBytes: 48291024 },
    opts: { attempts: 3, backoff: { type: 'exponential', delay: 2000 }, removeOnComplete: false },
    returnvalue: null,
    failedReason: 'OOMKilled: Worker ran out of memory processing 4K TIFF (48MB). Container limit: 512MB.',
    stacktrace: [
      'Error: ENOMEM: Cannot allocate memory, spawn',
      '    at ChildProcess.spawn (node:internal/child_process:438:19)',
      '    at Object.spawn (node:child_process:760:9)',
      '    at SharpProcessor.resize (/app/processors/sharp.ts:82:18)',
      '    at ImageWorker.process (/app/workers/image.ts:47:30)',
      '    at Worker.callProcessJob (/app/node_modules/taurusmq/src/worker.js:412:28)',
    ],
    processedOn: NOW - mins(12),
    finishedOn:  NOW - mins(11),
    timestamp:   NOW - mins(47),
    workerId: 'wkr_img_02',
    duration: 61000,
  },
  {
    id: 'job_c2d8e1f5a390',
    name: 'send-invoice',
    queueName: 'email-notifications',
    state: 'completed',
    priority: 5,
    attempts: 1,
    maxAttempts: 5,
    progress: 100,
    data: { userId: 'usr_bb921', invoiceId: 'inv_2026_08834', email: 'cto@acme.io', amount: 4299.00, currency: 'USD' },
    opts: { attempts: 5, backoff: { type: 'exponential', delay: 1000 } },
    returnvalue: { messageId: 'msg_SES_0x98f21a', delivered: true },
    processedOn: NOW - mins(3),
    finishedOn:  NOW - mins(2),
    timestamp:   NOW - mins(5),
    workerId: 'wkr_email_01',
    duration: 880,
  },
  {
    id: 'job_5e7b3c90d1a8',
    name: 'generate-monthly-report',
    queueName: 'report-generation',
    state: 'active',
    priority: 3,
    attempts: 2,
    maxAttempts: 3,
    progress: 67,
    data: { reportType: 'monthly-revenue', orgId: 'org_1829', month: '2026-05', format: 'pdf', includeCharts: true, rowCount: 48200 },
    opts: { attempts: 3, timeout: 120000 },
    returnvalue: null,
    processedOn: NOW - mins(8),
    timestamp:   NOW - mins(22),
    workerId: 'wkr_report_01',
    duration: undefined,
  },
  {
    id: 'job_9a1f6d2c8b47',
    name: 'dispatch-webhook',
    queueName: 'webhook-dispatch',
    state: 'waiting',
    priority: 2,
    attempts: 0,
    maxAttempts: 5,
    progress: 0,
    data: { endpoint: 'https://hooks.acme.io/v1/events', event: 'subscription.upgraded', payload: { plan: 'pro', userId: 'usr_9c3b1' }, secret: '[REDACTED]' },
    opts: { attempts: 5, backoff: { type: 'fixed', delay: 5000 }, timeout: 15000 },
    returnvalue: null,
    timestamp: NOW - mins(1),
  },
  {
    id: 'job_7d4e2a1b9c80',
    name: 'resize-thumbnail',
    queueName: 'image-processing',
    state: 'failed',
    priority: 1,
    attempts: 3,
    maxAttempts: 3,
    progress: 0,
    data: { originalKey: 's3://tmq-uploads/2026/06/13/photo_8mp.jpg', sizes: [128, 256, 512, 1024], quality: 85 },
    opts: { attempts: 3, backoff: { type: 'exponential', delay: 2000 } },
    returnvalue: null,
    failedReason: 'TimeoutError: Job exceeded timeout of 30000ms. Sharp worker did not respond.',
    stacktrace: [
      'TimeoutError: Job exceeded timeout of 30000ms',
      '    at Timeout._onTimeout (/app/node_modules/taurusmq/src/worker.js:289:18)',
      '    at listOnTimeout (node:internal/timers:573:17)',
      '    at processTimers (node:internal/timers:514:7)',
    ],
    processedOn: NOW - mins(31),
    finishedOn:  NOW - mins(30),
    timestamp:   NOW - mins(60),
    workerId: 'wkr_img_01',
    duration: 30100,
  },
  {
    id: 'job_3b8c5f2e1d94',
    name: 'sync-crm-contacts',
    queueName: 'data-sync',
    state: 'delayed',
    priority: 5,
    attempts: 1,
    maxAttempts: 5,
    progress: 0,
    data: { crmProvider: 'salesforce', orgId: 'org_9928', syncType: 'incremental', since: NOW - hrs(1) },
    opts: { attempts: 5, delay: mins(15), backoff: { type: 'exponential', delay: 5000 } },
    returnvalue: null,
    failedReason: 'RateLimitError: Salesforce API limit reached (150/150). Retry after 15 min.',
    timestamp: NOW - mins(18),
    delay: mins(15),
  },
];

// ─── Workers ──────────────────────────────────────────────────────────────────
function hb(miss: number[]) {
  return Array.from({ length: 30 }, (_, i) => miss.includes(i) ? 0 : 1);
}

export const WORKERS: Worker[] = [
  {
    id: 'wkr_email_01',
    hostname: 'worker-email-7d9f8b-xk2p9',
    pid: 18432,
    queueName: 'email-notifications',
    state: 'online',
    activeJobId: 'job_c2d8e1f5a390',
    concurrency: 4,
    processedJobs: 12847,
    failedJobs: 34,
    lastHeartbeat: NOW - 2000,
    startedAt: NOW - hrs(6),
    cpu: 18,
    memory: 142,
    memoryMax: 512,
    heartbeatHistory: hb([]),
  },
  {
    id: 'wkr_email_02',
    hostname: 'worker-email-7d9f8b-mn4r2',
    pid: 18567,
    queueName: 'email-notifications',
    state: 'idle',
    concurrency: 4,
    processedJobs: 11209,
    failedJobs: 28,
    lastHeartbeat: NOW - 3000,
    startedAt: NOW - hrs(6),
    cpu: 2,
    memory: 98,
    memoryMax: 512,
    heartbeatHistory: hb([]),
  },
  {
    id: 'wkr_img_01',
    hostname: 'worker-image-5c2a1f-p9x7k',
    pid: 22103,
    queueName: 'image-processing',
    state: 'stalled',
    concurrency: 2,
    processedJobs: 3201,
    failedJobs: 412,
    lastHeartbeat: NOW - mins(3),
    startedAt: NOW - hrs(2),
    cpu: 94,
    memory: 489,
    memoryMax: 512,
    heartbeatHistory: hb([27, 28, 29]),
  },
  {
    id: 'wkr_img_02',
    hostname: 'worker-image-5c2a1f-q1w8m',
    pid: 22341,
    queueName: 'image-processing',
    state: 'online',
    activeJobId: 'job_8f3a92b1c4e7',
    concurrency: 2,
    processedJobs: 2890,
    failedJobs: 479,
    lastHeartbeat: NOW - 4000,
    startedAt: NOW - hrs(2),
    cpu: 87,
    memory: 477,
    memoryMax: 512,
    heartbeatHistory: hb([24]),
  },
  {
    id: 'wkr_report_01',
    hostname: 'worker-report-8e3c9d-t4z1n',
    pid: 31029,
    queueName: 'report-generation',
    state: 'online',
    activeJobId: 'job_5e7b3c90d1a8',
    concurrency: 1,
    processedJobs: 891,
    failedJobs: 47,
    lastHeartbeat: NOW - 5000,
    startedAt: NOW - hrs(12),
    cpu: 61,
    memory: 298,
    memoryMax: 1024,
    heartbeatHistory: hb([14]),
  },
  {
    id: 'wkr_webhook_01',
    hostname: 'worker-webhook-2b1d8e-r7k3m',
    pid: 9182,
    queueName: 'webhook-dispatch',
    state: 'online',
    concurrency: 10,
    processedJobs: 48291,
    failedJobs: 182,
    lastHeartbeat: NOW - 1000,
    startedAt: NOW - hrs(24),
    cpu: 12,
    memory: 88,
    memoryMax: 256,
    heartbeatHistory: hb([]),
  },
];

// ─── Alerts ───────────────────────────────────────────────────────────────────
export const ALERTS: Alert[] = [
  {
    id: 'alrt_001',
    name: 'HighFailureRate',
    severity: 'critical',
    state: 'firing',
    queueName: 'image-processing',
    description: 'Queue image-processing failure rate exceeded 40% (current: 41.3%) for 5 minutes.',
    firedAt: NOW - mins(47),
    labels: { queue: 'image-processing', threshold: '10%', current: '41.3%' },
  },
  {
    id: 'alrt_002',
    name: 'WorkerStalledHeartbeat',
    severity: 'critical',
    state: 'firing',
    queueName: 'image-processing',
    description: 'Worker wkr_img_01 has not sent heartbeat in 3 minutes. Jobs may be stuck.',
    firedAt: NOW - mins(3),
    labels: { worker: 'wkr_img_01', last_seen: `${mins(3)}ms ago` },
  },
  {
    id: 'alrt_003',
    name: 'QueueDepthCritical',
    severity: 'critical',
    state: 'firing',
    queueName: 'image-processing',
    description: 'Waiting queue depth exceeded 3000 jobs. Backlog growing at 180 jobs/min.',
    firedAt: NOW - mins(38),
    labels: { queue: 'image-processing', depth: '3847', growth: '180/min' },
  },
  {
    id: 'alrt_004',
    name: 'HighP99Latency',
    severity: 'warning',
    state: 'firing',
    queueName: 'report-generation',
    description: 'P99 job latency for report-generation is 31s, exceeding SLA of 10s.',
    firedAt: NOW - mins(22),
    labels: { queue: 'report-generation', p99: '31000ms', sla: '10000ms' },
  },
  {
    id: 'alrt_005',
    name: 'WorkerMemoryPressure',
    severity: 'warning',
    state: 'firing',
    queueName: 'image-processing',
    description: 'Worker wkr_img_02 memory at 93% of limit (477MB / 512MB).',
    firedAt: NOW - mins(15),
    labels: { worker: 'wkr_img_02', memory: '477MB', limit: '512MB' },
  },
  {
    id: 'alrt_006',
    name: 'SalesforceRateLimit',
    severity: 'warning',
    state: 'pending',
    queueName: 'data-sync',
    description: 'Salesforce API rate limit triggered. data-sync queue backoff in effect.',
    firedAt: NOW - mins(18),
    labels: { queue: 'data-sync', provider: 'salesforce' },
  },
  {
    id: 'alrt_007',
    name: 'HighWebhookErrorRate',
    severity: 'info',
    state: 'resolved',
    queueName: 'webhook-dispatch',
    description: 'Webhook error rate briefly exceeded 5%. Issue self-resolved after 3 retries.',
    firedAt: NOW - hrs(2),
    resolvedAt: NOW - hrs(2) + mins(8),
    labels: { queue: 'webhook-dispatch', duration: '8min' },
  },
];

// ─── Event Stream ─────────────────────────────────────────────────────────────
export const EVENTS: EventStreamItem[] = [
  { id: 'ev_001', ts: NOW - 2000,     type: 'job_failed',          queueName: 'image-processing',    jobId: 'job_8f3a92b1c4e7', message: 'job_8f3a92b1c4e7 failed — OOMKilled after 61s (attempt 3/3)' },
  { id: 'ev_002', ts: NOW - 4000,     type: 'job_completed',       queueName: 'webhook-dispatch',    jobId: 'job_9a1f6d2c8b47', message: 'dispatch-webhook completed in 38ms' },
  { id: 'ev_003', ts: NOW - 8000,     type: 'job_completed',       queueName: 'email-notifications', jobId: 'job_c2d8e1f5a390', message: 'send-invoice completed in 880ms' },
  { id: 'ev_004', ts: NOW - mins(1),  type: 'alert_fired',         queueName: 'image-processing',    message: 'CRITICAL: WorkerStalledHeartbeat — wkr_img_01 last seen 3m ago' },
  { id: 'ev_005', ts: NOW - mins(2),  type: 'job_added',           queueName: 'webhook-dispatch',    jobId: 'job_9a1f6d2c8b47', message: 'dispatch-webhook enqueued (priority 2)' },
  { id: 'ev_006', ts: NOW - mins(3),  type: 'worker_disconnected', queueName: 'image-processing',    workerId: 'wkr_img_01', message: 'wkr_img_01 heartbeat lost — stall detected' },
  { id: 'ev_007', ts: NOW - mins(8),  type: 'job_started',         queueName: 'report-generation',   jobId: 'job_5e7b3c90d1a8', workerId: 'wkr_report_01', message: 'generate-monthly-report started on wkr_report_01' },
  { id: 'ev_008', ts: NOW - mins(12), type: 'job_failed',          queueName: 'image-processing',    jobId: 'job_8f3a92b1c4e7', message: 'process-upload failed — OOMKilled (attempt 2/3)' },
  { id: 'ev_009', ts: NOW - mins(15), type: 'alert_fired',         queueName: 'image-processing',    message: 'WARNING: WorkerMemoryPressure — wkr_img_02 at 93%' },
  { id: 'ev_010', ts: NOW - mins(18), type: 'job_retried',         queueName: 'data-sync',           jobId: 'job_3b8c5f2e1d94', message: 'sync-crm-contacts delayed 15min — Salesforce rate limit' },
  { id: 'ev_011', ts: NOW - mins(22), type: 'job_started',         queueName: 'report-generation',   jobId: 'job_5e7b3c90d1a8', message: 'generate-monthly-report restarted (attempt 2)' },
  { id: 'ev_012', ts: NOW - mins(31), type: 'job_failed',          queueName: 'image-processing',    jobId: 'job_7d4e2a1b9c80', message: 'resize-thumbnail failed — Timeout 30s (attempt 3/3)' },
  { id: 'ev_013', ts: NOW - mins(38), type: 'alert_fired',         queueName: 'image-processing',    message: 'CRITICAL: QueueDepthCritical — 3847 waiting' },
  { id: 'ev_014', ts: NOW - mins(47), type: 'alert_fired',         queueName: 'image-processing',    message: 'CRITICAL: HighFailureRate — 41.3% failure rate' },
];

// ─── Flow nodes (DAG) ─────────────────────────────────────────────────────────
export const FLOW_NODES: FlowNode[] = [
  { id: 'fn_1', jobId: 'job_flow_01', name: 'fetch-raw-data', state: 'completed', duration: 1240, startedAt: NOW - mins(30), finishedAt: NOW - mins(29), parentIds: [], childIds: ['fn_2', 'fn_3'], isCriticalPath: true },
  { id: 'fn_2', jobId: 'job_flow_02', name: 'validate-schema', state: 'completed', duration: 320, startedAt: NOW - mins(29), finishedAt: NOW - mins(28), parentIds: ['fn_1'], childIds: ['fn_4'], isCriticalPath: false },
  { id: 'fn_3', jobId: 'job_flow_03', name: 'enrich-from-crm', state: 'completed', duration: 8800, startedAt: NOW - mins(29), finishedAt: NOW - mins(20), parentIds: ['fn_1'], childIds: ['fn_4'], isCriticalPath: true },
  { id: 'fn_4', jobId: 'job_flow_04', name: 'merge-datasets', state: 'completed', duration: 2100, startedAt: NOW - mins(20), finishedAt: NOW - mins(17), parentIds: ['fn_2', 'fn_3'], childIds: ['fn_5', 'fn_6'], isCriticalPath: true },
  { id: 'fn_5', jobId: 'job_flow_05', name: 'generate-pdf', state: 'active', duration: undefined, startedAt: NOW - mins(17), finishedAt: undefined, parentIds: ['fn_4'], childIds: ['fn_7'], isCriticalPath: true },
  { id: 'fn_6', jobId: 'job_flow_06', name: 'send-slack-preview', state: 'waiting', duration: undefined, startedAt: undefined, finishedAt: undefined, parentIds: ['fn_4'], childIds: ['fn_7'], isCriticalPath: false },
  { id: 'fn_7', jobId: 'job_flow_07', name: 'notify-stakeholders', state: 'waiting', duration: undefined, startedAt: undefined, finishedAt: undefined, parentIds: ['fn_5', 'fn_6'], childIds: [], isCriticalPath: true },
];
